name: yolov8_pipeline
parameters:
  output_frame: null
  draw_func: null
  batch_size: 1
  batched_push_timeout: 40000
  telemetry:
    metrics:
      frame_period: 10000
pipeline:
  elements:
    # detector
    - element: nvinfer@detector
      name: yolov8m
      model:
        format: onnx
        model_file: yolov8m.onnx
        batch_size: ${parameters.batch_size}
        workspace_size: 6144
        label_file: labels.txt
        input:
          shape: [3,640,640]
          scale_factor: 0.0039215697906911373
          maintain_aspect_ratio: True
        output:
          layer_names: [ 'output0' ]
          converter:
            module: samples.yolov8_pipeline.converter
            class_name: TensorToBBoxConverter
            kwargs:
              confidence_threshold: 0.5
              nms_iou_threshold: 0.5
              top_k: 300

  sink:
    - element: devnull_sink
  source:
    element: uridecodebin
    properties:
      uri: file:///data/deepstream_sample_720p.mp4
